### ISSUE TITLE
mysign devs defaming us...

### ISSUE THREAD

**Issue by gliddd4** [WhySooooFurious/Stremio-Web-Clip#1]
I lost 50000000 billion bitcoin please fix

**Comment by WhySooooFurious** [comment]
glibb=skidd 

MySign developers blatantly defaming us, shows their maturity level.

I edited it to something else but reverted it back to showcase their maturity.

**Comment by MuahZain-Tech** [comment]
Hello @gliddd4 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Support Request](https://generalwebfixes.web.app/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!


> I lost 50000000 billion bitcoin please fix
